ticket_management_system/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

/*
    3 Interfaces:
    - ADMIN
    - LEADER
    - MEMBER
*/


Route::middleware(['auth'])->group(function(){  //, 'verifyUser'

    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/admin', 'AdminController@index')->name('admin.index');
    Route::get('/member', 'MemberController@index')->name('member.index');
    Route::put('/member/{member}', 'TaskController@update_to_approval')->name('task.update_to_approval');
    Route::resource('team', 'TeamController');
    Route::resource('task', 'TaskController');
    Route::post('/task/create', 'TaskController@storeBestMemberTask')->name('task.storeBestMemberTask');
    Route::put('/task/{task}', 'TaskController@update_reject_or_approve')->name('task.update_reject_or_approve');

    Route::get('/leader', 'LeaderController@index')->name('leader.index');
});

ticket_management_system/app/Team.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Team extends Model
{
    use SoftDeletes;

    protected $dates = ['published_at'];

    protected $fillable = [
        'team_name',
        'team_leader_id',
        'team_leader_name'
    ];

    // public function users() {
    //     return $this->belongsToMany(Users::class);
    // }
}

ticket_management_system/app/Http/Controllers/TeamController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\team\CreateTeamRequest;
use App\Team;
use App\User;
use App\User_teams;
use Illuminate\Http\Request;

class TeamController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $teams = Team::all();
        // $user_team = User_teams::all();
        // $users =  User::all();
        return view('team.index', compact([
            'teams'
            // 'user_team',
            // 'users'
        ]));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $users = User::where('in_team', 0)->where('role', "member")->get();
        // dd($users = User::where('in_team', 0)->get());

        return view('team.create', compact([
            'users'
        ]));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateTeamRequest $request)
    {
        $team_leader_name = User::where('id', $request->team_leader)->get('name');
       $team_data =  Team::create([
            'team_name'=>$request->team_name,
            'team_leader_id'=>$request->team_leader[0],
            'team_leader_name'=>$team_leader_name[0]->name,
            'published_at'=>$request->published_at
        ]);

        //Updating role to leader in users table
        User::update_role_to_leader($request->team_leader[0]);

        //updating the in_team status in User table
        for($i = 0; $i < sizeOf($request->team_members); $i++){
            User::update_in_team_status($request->team_members[$i]);

            User_teams::create([
                'users_id' =>$request->team_members[$i],
                'teams_id'=>$team_data->id
             ]);
        }
        

        return redirect(route('team.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Team  $team
     * @return \Illuminate\Http\Response
     */
    public function show(Team $team)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Team  $team
     * @return \Illuminate\Http\Response
     */
    public function edit(Team $team)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Team  $team
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Team $team)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Team  $team
     * @return \Illuminate\Http\Response
     */
    public function destroy(Team $team)
    {
        //
    }
}

ticket_management_system/resources/views/team/create.blade.php
@extends('layouts.components.layout')
@section('title','Ticket management | Ease to manage')

@section('main-content')
<!-- Begin Page Content -->
<div class="container-fluid">

<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between">
  <h1 class="h3 mb-4 text-gray-800">Add Category</h1>
  <a href="" class="d-none d-sm-inline-nlock btn btn-sm btn-primary shadow-sm">
      <i class="fas fa-list-ul fa-sm text-white"></i>
  </a>                  
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <div class="card shadow mb-4">
                <div class="card-header">
                    <h6 class="m-0 font-weight-bold text-primary">
                        <i class="fa fa-plus"></i>Create Team
                    </h6>
                </div>
              <!--END OF CARD HEADER-->
              
              <!--CARD BODY-->
              <div class="card-body">
                  <form action="{{ route('team.store') }}" method="POST">
                     @csrf
                      <div class="row" id="create_container">
                          <div class="col-md-6">
                              <div class="form-group">
                                <label for="team_name">Team Name</label>
                                <input type="text"
                                    value="{{ old('team_name') }}"
                                    class="form-control @error('team_name') is-invalid @enderror"
                                    name="team_name" id="team_name">
                                @error('team_name')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>

                            <div class="form-group">
                                <label for="team_leader">Team Leader</label>
                                <select name="team_leader[]"  class="form-control select2 team_leader select_leader">
                                    
                                </select>
                                @error('team_leader')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                          </div>
                          <div class="col-md-6">
                            <div class="form-group">
                                <label for="team_members">Team Members</label>
                                <select name="team_members[]" id="team_members"style="height: 124px;" class="form-control select2-use select-member" multiple="multiple">
                                    @foreach($users as $user)
                                        <option value="{{$user->id}}">{{$user->name}}</option>
                                    @endforeach
                                </select>
                                @error('team_members')
                                    <p class="text-danger">{{ $message }}</p>
                                @enderror
                            </div>
                          </div>
                  </div>
                  <div class="form-group">
                    <input type="submit" class="btn btn-primary " name="create-team" value="Create" id="create-team">
                  </div>
                  
                  </form>
              </div>
            </div>
        </div>
    </div>
</div>
</div>
<!-- /.container-fluid -->

@endsection

@section('page-level-scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/trix/1.2.3/trix.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    <script>
        $(document).ready(function(){
            $('.select2-use').select2({
                placeholder: 'Select Team Members...'
            });
        });
    </script>

    <script>
        $("#create_container").on('change', '.team_members', function(){
            alert("change");
        });
    </script>

    <script>
        // on select event
        $('.select-member').on('select2:select', function (e) {
            var data = e.params.data;
            // console.log(data.text);

            var newdata = {
                id: data.id,
                text: data.text
            };

            var newOption = new Option(newdata.text, newdata.id, false, false);
            $('.select_leader').append(newOption).trigger('change');

        });

        // on unselect event
        $('.select-member').on('select2:unselect', function (e) {
            var data = e.params.data;
            
            $(".select_leader").empty();
            var selected_info = $('.select-member').select2('data');
            var i;
            for(i=0;i<selected_info.length;i++){
                var newOption = new Option(selected_info[i].text, selected_info[i].id, false, false);
                $('.select_leader').append(newOption).trigger('change');
            }
        });
    </script>
@endsection

@section('page-level-styles')
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css">
@endsection

ticket_management_system/resources/views/team/index.blade.php
@extends('layouts.components.layout')
@section('title','Ticket management | Ease to manage')

@section('main-content')

<div class="container mt-4">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between">
    <h1 class="h3 mb-4 text-gray-800">All Teams</h1>
    <a href="" class="d-none d-sm-inline-nlock btn btn-sm btn-primary shadow-sm">
        <i class="fas fa-list-ul fa-sm text-white"></i>
    </a>                  
    </div>

    @foreach($teams as $team)
        <div class="card text-white bg-dark mb-3" style="max-width: 100%;">
        <div class="card-header">{{$team->team_name}}</div>
        <div class="card-body">
            <h5 class="card-title">{{$team->team_leader_name}} - Leader</h5>

<?php
    $users_in_team = App\User_teams::where('teams_id', $team->id)->get();
?>
            @foreach($users_in_team as $user)
                <!-- <p class="card-text"> -->
                    <?php
                        $user_info = App\User::where([
                            'id' => $user->users_id,
                            'role' => 'member'
                        ])->get();
                    // dd($user_info[0]->name);
                    ?>
                    @if(count($user_info) > 0)
                        <span class="btn badge-primary">{{ $user_info[0]->name }} / {{ $user_info[0]->role }}</span>
                    @endif
                <!-- </p> -->
            @endforeach
        </div>
        </div>
    @endforeach
</div>
@endsection

<!-- <button type="button" class="btn btn-primary">
  Notifications <span class="badge badge-light">4</span>
</button> -->