ticket_management_system/routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

/*
    3 Interfaces:
    - ADMIN
    - LEADER
    - MEMBER
*/


Route::middleware(['auth'])->group(function(){  //, 'verifyUser'

    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/admin', 'AdminController@index')->name('admin.index');
    Route::get('/member', 'MemberController@index')->name('member.index');
    Route::put('/member/{member}', 'TaskController@update_to_approval')->name('task.update_to_approval');
    Route::resource('team', 'TeamController');
    Route::resource('task', 'TaskController');
    Route::post('/task/create', 'TaskController@storeBestMemberTask')->name('task.storeBestMemberTask');
    Route::put('/task/{task}', 'TaskController@update_reject_or_approve')->name('task.update_reject_or_approve');

    Route::get('/leader', 'LeaderController@index')->name('leader.index');
});

ticket_management_system/resources/views/layouts/components/_navbar.blade.php
<div class="col-md-12 p-0">
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>
</div>

ticket_management_system/resources/views/layouts/components/_sidebar.blade.php
<div class="col-md-2" id="sidebar">
    <div class="logo-area">
        <p class="m-0">Ticket<span class="main-blue"> Management</span></p> 
        <!-- <hr> -->
    </div>
    <div class="div mt-5">
        <ul>
            <!-- Showing all teams -->
           @if(auth()->user()->isAdmin())
                <li><a href="{{ route('admin.index') }}"><span class="fas fa-home"></span>&nbsp; Home</a></li>
                <li><a href="{{ route('team.index') }}"><span class="fas fa-users"></span>&nbsp; All Teams</a></li>
                <li><a href="{{ route('team.create') }}"><span class="fas fa-plus"></span>&nbsp; Create Team</a></li>
            @elseif(auth()->user()->isLeader())
            <li><a href="{{ route('leader.index') }}">Home</a></li> 
                <li><a href="{{ route('task.create') }}"><span class="fas fa-plus"></span>&nbsp; Assign Task</a></li>
                <li>
                    <a href="{{ route('task.index') }}"><span class="fas fa-list"></span>&nbsp; View Tasks</a>
                    
                    @yield('notifications')
                </li>
           @else
                <li><a href="{{ route('member.index') }}"><span class="fas fa-home"></span>&nbsp; Home</a></li>
                <!-- <li><a href="#"><span class=""></span> View Task</a></li> -->
            @endif
            <li><a href="#">Other</a></li>
        </ul>

        @if(auth()->user()->isLeader())
            @if(URL::current() == 'http://localhost:8000/leader')
                <div class="notification-box bg-primary p-3" style="border-radius:10px;margin-top:150px;">
                    <p class="color-light pb-1 m-0" style="font-weight: 600;">Notifications:</p>
                    <div class="mb-2" style="margin-left:-20px;width:120%;background-color:#000C15;height:1px;opacity: 0.1;"></div>
                    @yield('notification-box-contents')
                </div>
            @endif
        @endif

    </div>
</div>

@section('page-level-styles')
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css">
@endsection

@section('page-level-scripts')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/js/all.min.js"></script>
@endsection

ticket_management_system/resources/views/layouts/components/layout.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@yield('title')</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta charset="utf-8">
    <meta name="author" content="John Doe">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0"/>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css">

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    @yield('page-level-styles')

</head>
<body>
    <div class="">
        @include('layouts.components._navbar')
        <div class="container-fluid">
            <div class="row">
                
                 @include('layouts.components._sidebar')

                <div class="col-md-10" style="max-width: 100%!important;">
                    @yield('main-content')
                </div>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/js/all.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.5.1/dist/chart.min.js"></script>
    @yield('page-level-scripts')

</body>
</html>